=== PRO-2684/transitio/userstyles.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "title": "Name",
                "pattern": "^.+$",
                "description": "The name of the style, preferably using only alphanumeric characters, hyphens and spaces and consistent with the style's `@name` metadata"
            },
            "author": {
                "type": "string",
                "title": "Author",
                "pattern": "^[a-zA-Z0-9\\-_]+$",
                "description": "The author's GitHub username"
            },
            "description": {
                "type": "string",
                "title": "Description",
                "pattern": "^.+$",
                "description": "A brief description of the style, preferably consistent with the style's `@description` metadata"
            },
            "preprocessor": {
                "type": "string",
                "title": "Preprocessor",
                "enum": ["none", "transitio", "stylus"],
                "description": "The preprocessor used for the style"
            },
            "link": {
                "type": "string",
                "title": "Homepage Link",
                "format": "uri",
                "description": "A link to the style's homepage or repository, preferably consistent with the style's `@homepageURL` metadata"
            },
            "download": {
                "type": "string",
                "title": "Download Link",
                "format": "uri",
                "description": "The download link for the style"
            }
        },
        "required": ["name", "author", "description", "preprocessor", "link", "download"]
    }
}

=== PRO-2684/transitio/userstyles.json
[
    {
        "name": "admin-s-green-hat",
        "author": "sileence114",
        "description": "让管理员戴回绿帽（将管理员头衔颜色重新改为绿色）",
        "preprocessor": "transitio",
        "link": "https://github.com/sileence114/ntqq_user_script/blob/main/README.md#admin-s-green-hat",
        "download": "https://raw.githubusercontent.com/sileence114/ntqq_user_script/refs/heads/main/css/admin-s-green-hat.css"
    },
    {
        "name": "Anti-Recall",
        "author": "Cranyozen",
        "description": "自用的适用于 anti-recall 撤回提示样式",
        "preprocessor": "transitio",
        "link": "https://gist.github.com/Cranyozen/320f90513b658ae82a9c7872f867a33f",
        "download": "https://gist.githubusercontent.com/Cranyozen/320f90513b658ae82a9c7872f867a33f/raw/76824fca4d93794551db82004dcd926151437537/anti-recall-css.css"
    },
    {
        "name": "auto-fold-chat-input-area",
        "author": "lamprose",
        "description": "消息输入框默认折叠有文字输入时展开",
        "preprocessor": "none",
        "link": "https://github.com/lamprose/transitio-css#auto-fold-chat-input-area",
        "download": "https://raw.githubusercontent.com/lamprose/transitio-css/refs/heads/main/auto-fold-chat-input-area.css"
    },
    {
        "name": "Avatar Float",
        "author": "PRO-2684",
        "description": "头像浮动",
        "preprocessor": "stylus",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#avatar-float",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/avatar-float.styl"
    },
    {
        "name": "Avatar The Bubbles",
        "author": "BingZi-233",
        "description": "头像描边",
        "preprocessor": "transitio",
        "link": "https://gist.github.com/BingZi-233/bfed496741624cc2e51aa7c9cdfca78a",
        "download": "https://gist.githubusercontent.com/BingZi-233/bfed496741624cc2e51aa7c9cdfca78a/raw/c9d47c1722cf574e7ac51f2bdbaf3736081be57d/avatar-the-bubbles.css"
    },
    {
        "name": "bubble-bg-color",
        "author": "EmptyDreams",
        "description": "修改自己发送的聊天气泡的背景色",
        "preprocessor": "transitio",
        "link": "https://gist.github.com/EmptyDreams/e1374d3e334904f1103bee1ff9087dc5",
        "download": "https://gist.githubusercontent.com/EmptyDreams/e1374d3e334904f1103bee1ff9087dc5/raw/e15a2b45214ea1fade76e0656aeae48cd561e2a9/bubble-bg-color.css"
    },
    {
        "name": "Bubble Show or Hide",
        "author": "GuestLiang",
        "description": "显示或隐藏用户自定义的气泡",
        "preprocessor": "transitio",
        "link": "https://github.com/Guest-Liang/Bubble-Show-or-Hide",
        "download": "https://raw.githubusercontent.com/Guest-Liang/Bubble-Show-or-Hide/refs/heads/main/bubble-show-or-hide.css"
    },
    {
        "name": "Customize More Menu",
        "author": "PRO-2684",
        "description": "自定义隐藏主界面更多菜单中的项目",
        "preprocessor": "stylus",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#customize-more-menu",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/customize-more-menu.styl"
    },
    {
        "name": "Customize Settings",
        "author": "PRO-2684",
        "description": "自定义隐藏 QQNT 原生设置界面选项",
        "preprocessor": "stylus",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#customize-settings",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/customize-settings.styl"
    },
    {
        "name": "Compact At List",
        "author": "PRO-2684",
        "description": "艾特建议面板更为紧凑",
        "preprocessor": "transitio",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#compact-at-list",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/compact-at-list.css"
    },
    {
        "name": "Chat The Bubbles",
        "author": "BingZi-233",
        "description": "气泡描边",
        "preprocessor": "transitio",
        "link": "https://gist.github.com/BingZi-233/0193165fa053f6d9e61140180d9a5995",
        "download": "https://gist.githubusercontent.com/BingZi-233/0193165fa053f6d9e61140180d9a5995/raw/28e923bab6a7452226ec1f6d6c7488b68fa4fe95/chat-the-bubbles.css"
    },
    {
        "name": "Demo Mode",
        "author": "PRO-2684",
        "description": "演示模式：模糊化部分元素",
        "preprocessor": "transitio",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#demo-mode",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/demo-mode.css"
    },
    {
        "name": "Focus Visible",
        "author": "PRO-2684",
        "description": "为聚焦元素添加可见的边框",
        "preprocessor": "stylus",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#focus-visible",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/focus-visible.styl"
    },
    {
        "name": "Font Color",
        "author": "nogodnodevil",
        "description": "自定义 QQNT 一些文字的颜色",
        "preprocessor": "none",
        "link": "https://github.com/nogodnodevil/Transitio--font-color",
        "download": "https://raw.githubusercontent.com/nogodnodevil/Transitio--font-color/refs/heads/main/font-color.css"
    },
    {
        "name": "Hide Emoticon Response",
        "author": "InfSein",
        "description": "移除右键消息上的表情回应",
        "preprocessor": "none",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#hide-emoticon-response",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/hide-emoticon-response.css"
    },
    {
        "name": "Hide Items",
        "author": "PRO-2684",
        "description": "隐藏一些元素",
        "preprocessor": "none",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#hide-items",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/hide-items.css"
    },
    {
        "name": "hide-level",
        "author": "SoudayoWwww",
        "description": "隐藏群内等级",
        "preprocessor": "transitio",
        "link": "https://github.com/SoudayoWwww/transitio-hide-level#hide-level",
        "download": "https://raw.githubusercontent.com/SoudayoWwww/transitio-hide-level/refs/heads/main/hide-level.css"
    },
    {
        "name": "Hide Lock",
        "author": "Shapaper233",
        "description": "隐藏侧边栏 \"更多\" 中倒数第四个按钮 (\"锁定\")",
        "preprocessor": "none",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#hide-lock",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/hide-lock.css"
    },
    {
        "name": "Hide Self",
        "author": "PRO-2684",
        "description": "隐藏自己的头像和昵称",
        "preprocessor": "none",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#hide-self",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/hide-self.css"
    },
    {
        "name": "Hide the import phone album function for certain interfaces",
        "author": "YatFanLan",
        "description": "隐藏某些界面的的导入手机相册功能",
        "preprocessor": "transitio",
        "link": "https://github.com/YatFanLan/Hide-importing-phone-photo-album",
        "download": "https://raw.githubusercontent.com/YatFanLan/Hide-importing-phone-photo-album/refs/heads/main/YatFanLan/Hide-importing-phone-photo-album"
    },
    {
        "name": "Highlight At",
        "author": "PRO-2684",
        "description": "高亮艾特",
        "preprocessor": "none",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#highlight-at",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/highlight-at.css"
    },
    {
        "name": "Image Viewer",
        "author": "PRO-2684",
        "description": "媒体查看器透明度修改",
        "preprocessor": "transitio",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#image-viewer",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/image-viewer.css"
    },
    {
        "name": "Imagesize",
        "author": "zhuoxin-lzk",
        "description": "限制图片和 gif 高度",
        "preprocessor": "none",
        "link": "https://github.com/zhuoxin-lzk/transitio-ImageSize",
        "download": "https://raw.githubusercontent.com/zhuoxin-lzk/transitio-ImageSize/refs/heads/main/ImageSize.css"
    },
    {
        "name": "Input Placeholder",
        "author": "PRO-2684",
        "description": "添加输入框提示（占位符）",
        "preprocessor": "transitio",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#input-placeholder",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/input-placeholder.css"
    },
    {
        "name": "Less Spacing",
        "author": "sileence114",
        "description": "减少元素间距",
        "preprocessor": "transitio",
        "link": "https://github.com/sileence114/ntqq_user_script/blob/main/README.md#less-spacing",
        "download": "https://raw.githubusercontent.com/sileence114/ntqq_user_script/refs/heads/main/css/less-spacing.css"
    },
    {
        "name": "Link Color",
        "author": "PRO-2684",
        "description": "链接动态颜色：悬浮/按下时显示相应颜色。",
        "preprocessor": "none",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#link-color",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/link-color.css"
    },
    {
        "name": "Lite Tools Recall Enhancement",
        "author": "Shapaper233",
        "description": "给 lite-tools 的撤回消息加上红色增强描边",
        "preprocessor": "none",
        "link": "https://github.com/PRO-2684/Transitio-user-css/#lite-tools-recall-enhancement",
        "download": "https://raw.githubusercontent.com/PRO-2684/Transitio-user-css/refs/heads/main/lite-tools-recall-enhancement.css"
    },
    {
        "name": "Message Img Transparent",
